<?php

/**
 * @file
 */

use Drupal\omkar_state_api\Event\BlogPublishedEvent;

/**
 * Implements hook_entity_insert().
 */
function omkar_state_api_entity_insert($entity) {
  if ($entity->getEntityTypeId() === 'node' && $entity->bundle() === 'blog' && $entity->isPublished()) {
    $dispatcher = \Drupal::service('event_dispatcher');

    $event = new BlogPublishedEvent($entity);

    $dispatcher->dispatch($event, BlogPublishedEvent::EVENT_NAME);

  }
}
